@extends("layouts.app")

@section("contentheader_title", "Inquiries")
@section("contentheader_description", "Inquiries generated by you.")
@section("section", "Inquiries")
@section("sub_section", "Listing")

@section("main-content")
<div class="box">
	<div class="box-header">
		<h3 class="box-title">Data Table With Full Features</h3>
	</div>
	<div class="box-body">
		<table id="example1" class="table table-bordered">
		<thead>
		<tr class="success">
			<th>Name</th>
			<th>Email</th>
			<th>Phone</th>
			<th>is Ref</th>
			<th>Action</th>
		</tr>
		</thead>
		<tbody>
			@foreach( $allInquiries as $inquiry )
				<tr>
					<td><b>{!! Html::linkRoute('inquiries.show', $inquiry->name, array($inquiry->id)) !!}</b></td>
					<td>{{ $inquiry->email }}</td>
					<td>{{ $inquiry->phone }}</td>
					<td>{{ $inquiry->ref }}</td>
					<td>{!! Html::linkRoute('inquiries.edit', 'Edit', array($inquiry->id), ['class'=>'btn btn-success btn-xs', 'style'=>'display:inline']) !!}
						{!! Form::open(['route' => ['inquiries.destroy', $inquiry->id], 'method' => 'delete', 'style'=>'display:inline']) !!}
							<input class="btn btn-danger btn-xs" type="submit" value="Delete" />
						{!! Form::close() !!}</td>
				</tr>
			@endforeach
		</tbody>
		</table>
	</div>
</div>
@endsection

@push('scripts')
<script src="{{ asset('/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('/plugins/datatables/dataTables.bootstrap.min.js') }}"></script>
<script>
$(function () {
	$("#example1").DataTable();
	/*
	$('#example2').DataTable({
		"paging": true,
		"lengthChange": false,
		"searching": false,
		"ordering": true,
		"info": true,
		"autoWidth": false
	});
	*/
});
</script>
@endpush