@extends("layouts.app")

@section("contentheader_title", "Inquiries")
@section("contentheader_description", "Inquiries generated by you.")
@section("section", "Inquiries")
@section("sub_section", "Listing")

@section("main-content")

<?php
use App\User;
?>
<div class="box">
	<div class="box-header">
		<h3 class="box-title">Inquiry Listing</h3>
		<button class="btn btn-success btn-sm pull-right" data-toggle="modal" data-target="#inquiryAddModal">Add New Inquiry</button>
	</div>
	<div class="box-body">
		<table id="example1" class="table table-bordered">
		<thead>
		<tr class="success">
			<th>ID</th>
			<th>Name</th>
			<th>Email</th>
			<th>Phone</th>
			<th>is Ref</th>
			@if(Auth::user()->user_type == "SUPER_ADMIN")
				<th>Owner</th>
			@endif
			<th>Comment</th>
			<th>Action</th>
		</tr>
		</thead>
		<tbody>
			@foreach( $allInquiries as $inquiry )
				<tr>
					<td>{!! $inquiry->id !!}</td>
					<td><b>{!! $inquiry->name !!}</b></td>
					<td>{{ $inquiry->email }}</td>
					<td>{{ $inquiry->phone }}</td>
					<td>
						{!! Form::open(['route' => ['inquiries.update_ajax', $inquiry->id], 'method' => 'update_ajax', 'style'=>'display:inline']) !!}
						<input name="ref_{!! $inquiry->id !!}" type="checkbox" @if($inquiry->ref == 1) checked="checked" @endif>
						
						<div class="Switch Ajax Round @if($inquiry->ref == 1) On @else Off @endif" inqid="{!! $inquiry->id !!}">
							<div class="Toggle"></div>
						</div>
						{!! Form::close() !!}
					</td>
					@if(Auth::user()->user_type == "SUPER_ADMIN")
						<td>{{ $users[$inquiry->owner]->name }}</td>
						<td><button class="commentInq btn @if(trim($inquiry->comment) != "") btn-warning @else btn-success @endif btn-xs pull-right" inq_id="{{ $inquiry->id }}" inq_name="{{ $inquiry->name }}" inq_comm="{{ $inquiry->comment }}">@if(trim($inquiry->comment) != "") Edit Comment @else Comment @endif</button></td>
					@else
						<td>@if(trim($inquiry->comment) != "")<button class="commentInq btn btn-success btn-xs pull-right" inq_id="{{ $inquiry->id }}" inq_name="{{ $inquiry->name }}" inq_comm="{{ $inquiry->comment }}"> Comment</button>@endif</td>
					@endif
					<td>{!! Html::linkRoute('inquiries.edit', 'Edit', array($inquiry->id), ['class'=>'btn btn-warning btn-xs', 'style'=>'display:inline;padding:2px 5px 3px 5px;']) !!}
						{!! Form::open(['route' => ['inquiries.destroy', $inquiry->id], 'method' => 'delete', 'style'=>'display:inline']) !!}
							<input class="btn btn-danger btn-xs" type="submit" value="Delete" />
						{!! Form::close() !!}</td>
				</tr>
			@endforeach
		</tbody>
		</table>
	</div>
</div>


<div class="modal fade" id="inquiryAddModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="myModalLabel">Add Inquiry</h4>
			</div>
			{!! Form::open(['action' => 'InquiryController@store']) !!}
			<div class="modal-body">
				<div class="box-body">
					<div class="form-group">
						{!! Form::label('name', 'Name :') !!}
                    	{!! Form::text('name', null, ['class'=>'form-control', 'placeholder'=>'Name']) !!}
					</div>
					<div class="form-group">
						{!! Form::label('email', 'Email :') !!}
                    	{!! Form::email('email', null, ['class'=>'form-control', 'placeholder'=>'Email']) !!}
					</div>
					<div class="form-group">
						{!! Form::label('phone', 'Phone :') !!}
                    	{!! Form::tel('phone', null, ['class'=>'form-control', 'placeholder'=>'Phone']) !!}
					</div>
					<div class="form-group">
						{!! Form::label('ref_add', 'Is Reference :') !!}
						
						<input id="ref_add" name="ref_add" type="checkbox" checked="checked" value="1">
						<div class="Switch Round On" style="vertical-align:top;margin-left:10px;">
							<div class="Toggle"></div>
						</div>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				{!! Form::submit( 'Submit', ['class'=>'btn btn-success']) !!}
			</div>
			{!! Form::close() !!}
		</div>
	</div>
</div>

@if(Auth::user()->user_type == "SUPER_ADMIN")
<div class="modal fade" id="inquiryCommentModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="myModalLabel">Comment Inquiry:</h4>
			</div>
			{!! Form::open(['route' => ['inquiries.update_ajax', 0], 'method' => 'update_ajax', 'id' => 'commentInqForm']) !!}
			<input type="hidden" name="inq_id" id="inq_id" value="0">
			<div class="modal-body">
				<div class="box-body">
					<div class="form-group">
						{!! Form::label('comment', 'Comment :') !!}
                    	{!! Form::text('comment', null, ['class'=>'form-control', 'placeholder'=>'Comment']) !!}
						<p class="error" style="display:none;color:#FF877E;margin-top:5px;"></p>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				{!! Form::submit( 'Submit', ['class'=>'btn btn-success']) !!}
			</div>
			{!! Form::close() !!}
		</div>
	</div>
</div>
@endif

@if(Auth::user()->user_type == "USER")
<div class="modal fade" id="inquiryCommentModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="myModalLabel">Comment Inquiry:</h4>
			</div>
			<div class="modal-body">
				<div class="box-body">
					<div class="form-group">
						{!! Form::label('comment', 'Comment :') !!}
                    	{!! Form::text('comment', null, ['class'=>'form-control', 'placeholder'=>'Comment']) !!}
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			</div>
		</div>
	</div>
</div>
@endif

@endsection

@push('scripts')
<script src="{{ asset('/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('/plugins/datatables/dataTables.bootstrap.min.js') }}"></script>
<script>
$(function () {
	$("#example1").DataTable();
	/*
	$('#example2').DataTable({
		"paging": true,
		"lengthChange": false,
		"searching": false,
		"ordering": true,
		"info": true,
		"autoWidth": false
	});
	*/
	@if(Auth::user()->user_type == "SUPER_ADMIN")
	
	$(".commentInq").on("click", function(){
		$('#inquiryCommentModal .modal-title').html("Comment Inquiry: " + $(this).attr("inq_name"));
		$('#inquiryCommentModal #inq_id').val($(this).attr("inq_id"));
		$('#inquiryCommentModal input[name="comment"]').val($(this).attr("inq_comm"));
		$('#inquiryCommentModal').modal('show');
		$('#inquiryCommentModal .error').html("");
		$('#inquiryCommentModal .error').css("display", "none");
	});
	
	$("#commentInqForm").submit(function(e){
		e.preventDefault();
		console.log("commentInqForm");
		
		var _token = $('#inquiryCommentModal input[name=_token]').val();
		
		$.ajax({
			type: "POST",
			url : "{{ url('/inquiries/update_ajax') }}",
			xhrFields: {
				withCredentials: true
			},
			data : {
				_token: _token,
				type: "UPDATE_COMMENT",
				inqid: $('#inquiryCommentModal #inq_id').val(),
				comment: $('#inquiryCommentModal input[name="comment"]').val(),
			},
			success : function(data){
				console.log(data);
				if(data.success == true) {
					$('#inquiryCommentModal').modal('hide');
					$('#inquiryCommentModal input[name="comment"]').val("");
					$('#inquiryCommentModal .error').html("");
					$('#inquiryCommentModal .error').css("display", "none");
					window.location.reload();
				} else {
					console.log("Fail");
					$('#inquiryCommentModal').modal({'show':true});
					$('#inquiryCommentModal .error').html("Error: " + data.error);
					$('#inquiryCommentModal .error').css("display", "block");
				}
				
			}
		});
		$('#inquiryCommentModal').modal({'show':false});
	});
	@else
	
	$(".commentInq").on("click", function(){
		$('#inquiryCommentModal .modal-title').html("Comment Inquiry: " + $(this).attr("inq_name"));
		$('#inquiryCommentModal input[name="comment"]').val($(this).attr("inq_comm"));
		$('#inquiryCommentModal').modal('show');
	});
	
	@endif
	
	$('.Switch.Ajax').click(function() {
		var state = "false";
		if ($(this).hasClass('On')){
			state = "false";
		} else {
			state = "true";
		}
		var _token = $(this).parent().find('#inquiryAddModal input[name=_token]').val();
		$.ajax({
			type: "POST",
			url : "{{ url('/inquiries/update_ajax') }}",
			xhrFields: {
				withCredentials: true
			},
			data : {
				_token: _token,
				type: "UPDATE_REF",
				inqid: $(this).attr("inqid"),
				state: state,
			},
			success : function(data){
				console.log(data);
			}
		});
		
	});
	
});
</script>
@endpush