@extends("layouts.app")

@section("contentheader_title", "Inquiries")
@section("contentheader_description", "Inquiries generated by you.")
@section("section", "Inquiries")
@section("sub_section", "Listing")

@section("main-content")
<div class="box">
	<div class="box-header">
		<h3 class="box-title">Inquiry Listing</h3>
		<button class="btn btn-success btn-sm pull-right" data-toggle="modal" data-target="#inquiryAddModal">Add New Inquiry</button>
	</div>
	<div class="box-body">
		<table id="example1" class="table table-bordered">
		<thead>
		<tr class="success">
			<th>ID</th>
			<th>Name</th>
			<th>Email</th>
			<th>Phone</th>
			<th>is Ref</th>
			<th>Action</th>
		</tr>
		</thead>
		<tbody>
			@foreach( $allInquiries as $inquiry )
				<tr>
					<td>{!! $inquiry->id !!}</td>
					<td><b>{!! $inquiry->name !!}</b></td>
					<td>{{ $inquiry->email }}</td>
					<td>{{ $inquiry->phone }}</td>
					<td>
						{!! Form::open(['route' => ['inquiries.update_ajax', $inquiry->id], 'method' => 'update_ajax', 'style'=>'display:inline']) !!}
						<input name="ref_{!! $inquiry->id !!}" type="checkbox" @if($inquiry->ref == 1) checked="checked" @endif>
						
						<div class="Switch Ajax Round @if($inquiry->ref == 1) On @else Off @endif" inqid="{!! $inquiry->id !!}">
							<div class="Toggle"></div>
						</div>
						{!! Form::close() !!}
					</td>
					<td>{!! Html::linkRoute('inquiries.edit', 'Edit', array($inquiry->id), ['class'=>'btn btn-warning btn-xs', 'style'=>'display:inline;padding:2px 5px 3px 5px;']) !!}
						{!! Form::open(['route' => ['inquiries.destroy', $inquiry->id], 'method' => 'delete', 'style'=>'display:inline']) !!}
							<input class="btn btn-danger btn-xs" type="submit" value="Delete" />
						{!! Form::close() !!}</td>
				</tr>
			@endforeach
		</tbody>
		</table>
	</div>
</div>


<div class="modal fade" id="inquiryAddModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="myModalLabel">Add Inquiry</h4>
			</div>
			{!! Form::open(['action' => 'InquiryController@store']) !!}
			<div class="modal-body">
				<div class="box-body">
					<div class="form-group">
						{!! Form::label('name', 'Name :') !!}
                    	{!! Form::text('name', null, ['class'=>'form-control', 'placeholder'=>'Name']) !!}
					</div>
					<div class="form-group">
						{!! Form::label('email', 'Email :') !!}
                    	{!! Form::email('email', null, ['class'=>'form-control', 'placeholder'=>'Email']) !!}
					</div>
					<div class="form-group">
						{!! Form::label('phone', 'Phone :') !!}
                    	{!! Form::tel('phone', null, ['class'=>'form-control', 'placeholder'=>'Phone']) !!}
					</div>
					<div class="form-group">
						{!! Form::label('ref_add', 'Is Reference :') !!}
						
						<input id="ref_add" name="ref_add" type="checkbox" checked="checked" value="1">
						<div class="Switch Round On" style="vertical-align:top;margin-left:10px;">
							<div class="Toggle"></div>
						</div>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				{!! Form::submit( 'Submit', ['class'=>'btn btn-success']) !!}
			</div>
			{!! Form::close() !!}
		</div>
	</div>
</div>

@endsection

@push('scripts')
<script src="{{ asset('/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('/plugins/datatables/dataTables.bootstrap.min.js') }}"></script>
<script>
$(function () {
	$("#example1").DataTable();
	/*
	$('#example2').DataTable({
		"paging": true,
		"lengthChange": false,
		"searching": false,
		"ordering": true,
		"info": true,
		"autoWidth": false
	});
	*/
	
	$('.Switch.Ajax').click(function() {
		var state = "false";
		if ($(this).hasClass('On')){
			state = "false";
		} else {
			state = "true";
		}
		var _token = $(this).parent().find('input[name=_token]').val();
		$.ajax({
			type: "POST",
			url : "{{ url('/inquiries/update_ajax') }}",
			xhrFields: {
				withCredentials: true
			},
			data : {
				_token: _token,
				type: "UPDATE_REF",
				inqid: $(this).attr("inqid"),
				state: state,
			},
			success : function(data){
				console.log(data);
			}
		});
		
	});
	
});
</script>
@endpush